version: '3.8'
services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb_jenkins
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: fadic123
      MYSQL_DATABASE: laboratorio_bd
      MYSQL_USER: laboratorio
      MYSQL_PASSWORD: fadic123
    ports:
      - "3307:3306"
    volumes:
      - ./docker/estructura.sql:/docker-entrypoint-initdb.d/estructura.sql

  app:
    build: .
    container_name: laboratorio_app
    depends_on:
      - mariadb  # ✅ nombre del servicio, NO el container_name
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mariadb:3306/laboratorio_bd  # ✅ igual
      SPRING_DATASOURCE_USERNAME: laboratorio
      SPRING_DATASOURCE_PASSWORD: fadic123
